# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/security/osxminecraft/src/lua/CMakeLists.txt\
/Users/security/osxminecraft/src/lua/src/CMakeLists.txt
	/opt/local/bin/cmake -H/Users/security/osxminecraft -B/Users/security/osxminecraft
